bug fixes for v1beta1 and some typo in README.md
aws/cluster-api-provider-cloudstack pull request #24
Opened 2022-02-07 16:26 UTC by wanyufe

*metadata and template fix for v1beta1:*

*Description of changes:*
metadata clusterctl needs to be v1alpha3
and templates infrastructure for cloudstack should be v1beta1
some typo in README.md

*Testing performed:*
test-thing passed

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-02-07 16:31 UTC, jweite-amazon commented
Would the changes to cluster-template.yaml have to be applied to the other template flavors too?

2022-02-07 18:12 UTC, maxdrib approved these changes

2022-02-09 18:55 UTC, wongni commented on templates/cluster-template.yaml
>    infrastructureTemplate:
Does 'infrastructureTemplate' work with clusterctl v1.0.0+?
In my case, I had to replace this to the following 
```
  machineTemplate:
    infrastructureRef:
```

2022-02-09 18:57 UTC, wongni requested changes
Please update the other template files under template/ folder
- cluster-template-managed-ssh.yaml
- cluster-template-ssh-material.yaml

2022-02-10 13:10 UTC, jweite-amazon commented on README.md
> +    clusterctl generate cluster capc-cluster \
Is the cluster name param strictly needed, given that it's defined in the CLUSTER_NAME env var that precedes it?  If it is, then lets remove it from the env vars.  (clusterctl should substitute it into the template either way AFAIK).

2022-02-22 21:21 UTC, wanyufe commented
Since the changes/fixes had already been in other PRs, closing this PR.

2022-02-22 21:21 UTC, closed without merging