Fix/tilt fixup
aws/cluster-api-provider-cloudstack pull request #7
Opened 2022-01-18 22:52 UTC by rejoshed

*Issue #* N/A

*Description of changes:*
Some small fixes to make `make tilt-up` work.

*Testing performed:*
Checkout a fresh clone and try `make tilt-up`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-18 22:53 UTC, rejoshed commented on README.md
> -cluster-api-provider-cloudstack-staging % KUBECONFIG=capc-cluster.kubeconfig kubectl get pods -A
This is just cleanup that I tossed in this branch.

2022-01-18 22:57 UTC, maxdrib requested changes

2022-01-18 22:57 UTC, maxdrib commented on Makefile
> +	export CLOUDSTACK_B64ENCODED_SECRET=$$(base64 -i cloud-config) && cd cluster-api && tilt up
double $?

2022-01-18 22:58 UTC, rejoshed commented on Makefile
> +	export CLOUDSTACK_B64ENCODED_SECRET=$$(base64 -i cloud-config) && cd cluster-api && tilt up
Have to escape the makefile $ first.

2022-01-19 15:03 UTC, maxdrib approved these changes

2022-01-19 17:46 UTC, merged